### ISSUE TITLE
Giving failed replay returns an error.

### ISSUE THREAD

**Issue by xDololow** [rgbeing/osu-aim-analyzer#1]
Error in quietion:
![image](https://github.com/rgbeing/osu-aim-analyzer/assets/26763912/8d449cf2-440f-4c6c-81a8-47fc7fa2c2a9)

**Comment by rgbeing** [comment]
Can I know what map triggered the error? If can, I would be appreciate if you send me the replay file caused the error.

**Comment by xDololow** [comment]
Replay: https://drive.google.com/uc?id=1fQiKFp3waoVbuE-Bi2a4ZpPTsjgiJ0MS
Map: https://osu.ppy.sh/beatmapsets/1820756#osu/3753144

**Comment by xDololow** [comment]
Also this map returns an error with pass replay: https://osu.ppy.sh/beatmapsets/4428#osu/24233
Replay: https://drive.google.com/uc?id=1toYCUnMip6LhT853hwVtJALKtDSUcksF

![image](https://github.com/rgbeing/osu-aim-analyzer/assets/26763912/194273f2-0da9-48c0-8f9f-b5287c921134)

**Comment by rgbeing** [comment]
Given issues are settled, and now released as 1.0.3.

Thank you for your contribution!
