### ISSUE TITLE
Incorrect colour labels

### ISSUE THREAD

**Issue by ghost** [rgbeing/osu-aim-analyzer#2]
The program currently states that green indicates a significant issue, whilst red is insignificant. This is not the same as what the highlighted values indicate - it is the other way around (red is significantly off, whilst green is insignificant).

**Comment by rgbeing** [comment]
Actually significance is somewhat desired result in statistical reasoning-that is why a significant result takes green background. There were similar feedbacks personally so far, but I have no plan to change this currently.
